-- Rename all camelCase columns/indexes/constraints to snake_case
-- Tables already snake_case via @@map. Schema gets @map() per scalar field
-- so Prisma client field names stay camelCase (zero TS code churn).

-- ============================================================
-- 329 columns
-- ============================================================
ALTER TABLE "members" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "members" RENAME COLUMN "phoneCode" TO "phone_code";
ALTER TABLE "members" RENAME COLUMN "fullName" TO "full_name";
ALTER TABLE "members" RENAME COLUMN "firstName" TO "first_name";
ALTER TABLE "members" RENAME COLUMN "lastName" TO "last_name";
ALTER TABLE "members" RENAME COLUMN "passwordHash" TO "password_hash";
ALTER TABLE "members" RENAME COLUMN "passwordAlgo" TO "password_algo";
ALTER TABLE "members" RENAME COLUMN "googleSub" TO "google_sub";
ALTER TABLE "members" RENAME COLUMN "avatarUrl" TO "avatar_url";
ALTER TABLE "members" RENAME COLUMN "coverUrl" TO "cover_url";
ALTER TABLE "members" RENAME COLUMN "isActive" TO "is_active";
ALTER TABLE "members" RENAME COLUMN "isVerified" TO "is_verified";
ALTER TABLE "members" RENAME COLUMN "isPhoneVerified" TO "is_phone_verified";
ALTER TABLE "members" RENAME COLUMN "isMuted" TO "is_muted";
ALTER TABLE "members" RENAME COLUMN "isBanned" TO "is_banned";
ALTER TABLE "members" RENAME COLUMN "affiliateCode" TO "affiliate_code";
ALTER TABLE "members" RENAME COLUMN "affiliateBased" TO "affiliate_based";
ALTER TABLE "members" RENAME COLUMN "inviterId" TO "inviter_id";
ALTER TABLE "members" RENAME COLUMN "inviterNetworkId" TO "inviter_network_id";
ALTER TABLE "members" RENAME COLUMN "registerFrom" TO "register_from";
ALTER TABLE "members" RENAME COLUMN "utmSource" TO "utm_source";
ALTER TABLE "members" RENAME COLUMN "utmContent" TO "utm_content";
ALTER TABLE "members" RENAME COLUMN "scheduledDeletionAt" TO "scheduled_deletion_at";
ALTER TABLE "members" RENAME COLUMN "lastActiveAt" TO "last_active_at";
ALTER TABLE "members" RENAME COLUMN "notificationsEnabled" TO "notifications_enabled";
ALTER TABLE "members" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "members" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "member_profiles" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "member_profiles" RENAME COLUMN "countryId" TO "country_id";
ALTER TABLE "member_profiles" RENAME COLUMN "provinceId" TO "province_id";
ALTER TABLE "member_profiles" RENAME COLUMN "cityId" TO "city_id";
ALTER TABLE "member_profiles" RENAME COLUMN "districtId" TO "district_id";
ALTER TABLE "member_profiles" RENAME COLUMN "postalCode" TO "postal_code";
ALTER TABLE "member_profiles" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "devices" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "devices" RENAME COLUMN "deviceId" TO "device_id";
ALTER TABLE "devices" RENAME COLUMN "fcmToken" TO "fcm_token";
ALTER TABLE "devices" RENAME COLUMN "lastSeenAt" TO "last_seen_at";
ALTER TABLE "devices" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "refresh_tokens" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "refresh_tokens" RENAME COLUMN "clientType" TO "client_type";
ALTER TABLE "refresh_tokens" RENAME COLUMN "expiresAt" TO "expires_at";
ALTER TABLE "refresh_tokens" RENAME COLUMN "revokedAt" TO "revoked_at";
ALTER TABLE "refresh_tokens" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "otp_codes" RENAME COLUMN "expiresAt" TO "expires_at";
ALTER TABLE "otp_codes" RENAME COLUMN "usedAt" TO "used_at";
ALTER TABLE "otp_codes" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "pra_members" RENAME COLUMN "affiliateMemberId" TO "affiliate_member_id";
ALTER TABLE "pra_members" RENAME COLUMN "networkId" TO "network_id";
ALTER TABLE "pra_members" RENAME COLUMN "expiresAt" TO "expires_at";
ALTER TABLE "pra_members" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "countries" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "provinces" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "provinces" RENAME COLUMN "countryId" TO "country_id";
ALTER TABLE "cities" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "cities" RENAME COLUMN "provinceId" TO "province_id";
ALTER TABLE "districts" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "districts" RENAME COLUMN "cityId" TO "city_id";
ALTER TABLE "banners" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "banners" RENAME COLUMN "imageUrl" TO "image_url";
ALTER TABLE "banners" RENAME COLUMN "linkUrl" TO "link_url";
ALTER TABLE "banners" RENAME COLUMN "isActive" TO "is_active";
ALTER TABLE "banners" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "products" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "products" RENAME COLUMN "iapProductId" TO "iap_product_id";
ALTER TABLE "products" RENAME COLUMN "descriptionHtml" TO "description_html";
ALTER TABLE "products" RENAME COLUMN "marketingLink" TO "marketing_link";
ALTER TABLE "products" RENAME COLUMN "sellingPoints" TO "selling_points";
ALTER TABLE "products" RENAME COLUMN "isActive" TO "is_active";
ALTER TABLE "products" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "products" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "courses" RENAME COLUMN "productId" TO "product_id";
ALTER TABLE "courses" RENAME COLUMN "legacyCourseId" TO "legacy_course_id";
ALTER TABLE "courses" RENAME COLUMN "durationMin" TO "duration_min";
ALTER TABLE "courses" RENAME COLUMN "contentRef" TO "content_ref";
ALTER TABLE "course_enrollment" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "course_enrollment" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "course_enrollment" RENAME COLUMN "courseId" TO "course_id";
ALTER TABLE "course_enrollment" RENAME COLUMN "dateStart" TO "date_start";
ALTER TABLE "course_enrollment" RENAME COLUMN "dateEnd" TO "date_end";
ALTER TABLE "course_enrollment" RENAME COLUMN "expiredDate" TO "expired_date";
ALTER TABLE "course_enrollment" RENAME COLUMN "isCanceled" TO "is_canceled";
ALTER TABLE "course_enrollment" RENAME COLUMN "cancelationReason" TO "cancelation_reason";
ALTER TABLE "course_enrollment" RENAME COLUMN "certificateCode" TO "certificate_code";
ALTER TABLE "course_enrollment" RENAME COLUMN "certificateCreated" TO "certificate_created";
ALTER TABLE "course_enrollment" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "course_enrollment" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "course_sections" RENAME COLUMN "legacySectionId" TO "legacy_section_id";
ALTER TABLE "course_sections" RENAME COLUMN "courseId" TO "course_id";
ALTER TABLE "course_sections" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "course_lessons" RENAME COLUMN "legacyLessonId" TO "legacy_lesson_id";
ALTER TABLE "course_lessons" RENAME COLUMN "sectionId" TO "section_id";
ALTER TABLE "course_lessons" RENAME COLUMN "slidesData" TO "slides_data";
ALTER TABLE "course_lessons" RENAME COLUMN "lessonStatus" TO "lesson_status";
ALTER TABLE "course_lessons" RENAME COLUMN "isPreview" TO "is_preview";
ALTER TABLE "course_lessons" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "reviews" RENAME COLUMN "productId" TO "product_id";
ALTER TABLE "reviews" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "reviews" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "reviews" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "topics" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "topics" RENAME COLUMN "networkId" TO "network_id";
ALTER TABLE "topics" RENAME COLUMN "iconUrl" TO "icon_url";
ALTER TABLE "topics" RENAME COLUMN "iconType" TO "icon_type";
ALTER TABLE "topics" RENAME COLUMN "isActive" TO "is_active";
ALTER TABLE "topics" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "topic_join_requests" RENAME COLUMN "topicId" TO "topic_id";
ALTER TABLE "topic_join_requests" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "topic_join_requests" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "topic_join_requests" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "topic_subscriptions" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "topic_subscriptions" RENAME COLUMN "topicId" TO "topic_id";
ALTER TABLE "topic_subscriptions" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "posts" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "posts" RENAME COLUMN "authorId" TO "author_id";
ALTER TABLE "posts" RENAME COLUMN "topicId" TO "topic_id";
ALTER TABLE "posts" RENAME COLUMN "networkId" TO "network_id";
ALTER TABLE "posts" RENAME COLUMN "postType" TO "post_type";
ALTER TABLE "posts" RENAME COLUMN "imageUrls" TO "image_urls";
ALTER TABLE "posts" RENAME COLUMN "videoUrl" TO "video_url";
ALTER TABLE "posts" RENAME COLUMN "embedUrl" TO "embed_url";
ALTER TABLE "posts" RENAME COLUMN "publishStatus" TO "publish_status";
ALTER TABLE "posts" RENAME COLUMN "publishAt" TO "publish_at";
ALTER TABLE "posts" RENAME COLUMN "countLike" TO "count_like";
ALTER TABLE "posts" RENAME COLUMN "countComment" TO "count_comment";
ALTER TABLE "posts" RENAME COLUMN "countReplies" TO "count_replies";
ALTER TABLE "posts" RENAME COLUMN "viewCount" TO "view_count";
ALTER TABLE "posts" RENAME COLUMN "isPinned" TO "is_pinned";
ALTER TABLE "posts" RENAME COLUMN "engagedAt" TO "engaged_at";
ALTER TABLE "posts" RENAME COLUMN "isDeleted" TO "is_deleted";
ALTER TABLE "posts" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "posts" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "post_likes" RENAME COLUMN "postId" TO "post_id";
ALTER TABLE "post_likes" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "post_likes" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "post_reports" RENAME COLUMN "postId" TO "post_id";
ALTER TABLE "post_reports" RENAME COLUMN "reporterId" TO "reporter_id";
ALTER TABLE "post_reports" RENAME COLUMN "categoryId" TO "category_id";
ALTER TABLE "post_reports" RENAME COLUMN "networkId" TO "network_id";
ALTER TABLE "post_reports" RENAME COLUMN "reportStatus" TO "report_status";
ALTER TABLE "post_reports" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "comments" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "comments" RENAME COLUMN "postId" TO "post_id";
ALTER TABLE "comments" RENAME COLUMN "authorId" TO "author_id";
ALTER TABLE "comments" RENAME COLUMN "parentId" TO "parent_id";
ALTER TABLE "comments" RENAME COLUMN "imageUrls" TO "image_urls";
ALTER TABLE "comments" RENAME COLUMN "embedUrl" TO "embed_url";
ALTER TABLE "comments" RENAME COLUMN "countLike" TO "count_like";
ALTER TABLE "comments" RENAME COLUMN "countReplies" TO "count_replies";
ALTER TABLE "comments" RENAME COLUMN "isDeleted" TO "is_deleted";
ALTER TABLE "comments" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "comments" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "comment_likes" RENAME COLUMN "commentId" TO "comment_id";
ALTER TABLE "comment_likes" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "comment_likes" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "networks" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "networks" RENAME COLUMN "iconUrl" TO "icon_url";
ALTER TABLE "networks" RENAME COLUMN "bannerUrl" TO "banner_url";
ALTER TABLE "networks" RENAME COLUMN "countMember" TO "count_member";
ALTER TABLE "networks" RENAME COLUMN "memberQuota" TO "member_quota";
ALTER TABLE "networks" RENAME COLUMN "isPaid" TO "is_paid";
ALTER TABLE "networks" RENAME COLUMN "isPublic" TO "is_public";
ALTER TABLE "networks" RENAME COLUMN "isHelpdesk" TO "is_helpdesk";
ALTER TABLE "networks" RENAME COLUMN "isActive" TO "is_active";
ALTER TABLE "networks" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "network_member_requests" RENAME COLUMN "networkId" TO "network_id";
ALTER TABLE "network_member_requests" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "network_member_requests" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "network_member_requests" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "network_banned_members" RENAME COLUMN "networkId" TO "network_id";
ALTER TABLE "network_banned_members" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "network_banned_members" RENAME COLUMN "bannedAt" TO "banned_at";
ALTER TABLE "network_team_members" RENAME COLUMN "networkId" TO "network_id";
ALTER TABLE "network_team_members" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "network_team_members" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "network_members" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "network_members" RENAME COLUMN "networkId" TO "network_id";
ALTER TABLE "network_members" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "network_members" RENAME COLUMN "joinedAt" TO "joined_at";
ALTER TABLE "network_members" RENAME COLUMN "isMuted" TO "is_muted";
ALTER TABLE "network_tags" RENAME COLUMN "networkId" TO "network_id";
ALTER TABLE "network_tags" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "report_categories" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "report_categories" RENAME COLUMN "isActive" TO "is_active";
ALTER TABLE "report_categories" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "member_reports" RENAME COLUMN "reporterId" TO "reporter_id";
ALTER TABLE "member_reports" RENAME COLUMN "targetId" TO "target_id";
ALTER TABLE "member_reports" RENAME COLUMN "categoryId" TO "category_id";
ALTER TABLE "member_reports" RENAME COLUMN "networkId" TO "network_id";
ALTER TABLE "member_reports" RENAME COLUMN "reportStatus" TO "report_status";
ALTER TABLE "member_reports" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "notifications" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "notifications" RENAME COLUMN "networkId" TO "network_id";
ALTER TABLE "notifications" RENAME COLUMN "notifGroup" TO "notif_group";
ALTER TABLE "notifications" RENAME COLUMN "dedupeKey" TO "dedupe_key";
ALTER TABLE "notifications" RENAME COLUMN "seenAt" TO "seen_at";
ALTER TABLE "notifications" RENAME COLUMN "readAt" TO "read_at";
ALTER TABLE "notifications" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "notification_mutes" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "notification_mutes" RENAME COLUMN "refId" TO "ref_id";
ALTER TABLE "notification_mutes" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "affiliate_programs" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "affiliate_programs" RENAME COLUMN "productId" TO "product_id";
ALTER TABLE "affiliate_programs" RENAME COLUMN "isActive" TO "is_active";
ALTER TABLE "affiliate_programs" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "affiliate_programs" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "member_affiliators" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "member_affiliators" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "member_affiliators" RENAME COLUMN "programId" TO "program_id";
ALTER TABLE "member_affiliators" RENAME COLUMN "exitState" TO "exit_state";
ALTER TABLE "member_affiliators" RENAME COLUMN "exitAt" TO "exit_at";
ALTER TABLE "member_affiliators" RENAME COLUMN "isActive" TO "is_active";
ALTER TABLE "member_affiliators" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "member_affiliators" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "recipientId" TO "recipient_id";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "affiliatorId" TO "affiliator_id";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "programId" TO "program_id";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "productId" TO "product_id";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "paymentId" TO "payment_id";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "paymentLegacyId" TO "payment_legacy_id";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "buyerMemberId" TO "buyer_member_id";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "affiliateBased" TO "affiliate_based";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "schemaType" TO "schema_type";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "productPrice" TO "product_price";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "voucherAmount" TO "voucher_amount";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "commissionRate" TO "commission_rate";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "approvedAt" TO "approved_at";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "voidedAt" TO "voided_at";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "voidedBy" TO "voided_by";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "voidedReason" TO "voided_reason";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "attributionVisitId" TO "attribution_visit_id";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "affiliate_commissions" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "affiliate_visits" RENAME COLUMN "programId" TO "program_id";
ALTER TABLE "affiliate_visits" RENAME COLUMN "affiliatorMemberId" TO "affiliator_member_id";
ALTER TABLE "affiliate_visits" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "affiliate_visits" RENAME COLUMN "utmSource" TO "utm_source";
ALTER TABLE "affiliate_visits" RENAME COLUMN "utmMedium" TO "utm_medium";
ALTER TABLE "affiliate_visits" RENAME COLUMN "utmCampaign" TO "utm_campaign";
ALTER TABLE "affiliate_visits" RENAME COLUMN "utmContent" TO "utm_content";
ALTER TABLE "affiliate_visits" RENAME COLUMN "utmTerm" TO "utm_term";
ALTER TABLE "affiliate_visits" RENAME COLUMN "adId" TO "ad_id";
ALTER TABLE "affiliate_visits" RENAME COLUMN "adNetwork" TO "ad_network";
ALTER TABLE "affiliate_visits" RENAME COLUMN "ipAddress" TO "ip_address";
ALTER TABLE "affiliate_visits" RENAME COLUMN "userAgent" TO "user_agent";
ALTER TABLE "affiliate_visits" RENAME COLUMN "deviceId" TO "device_id";
ALTER TABLE "affiliate_visits" RENAME COLUMN "appVersion" TO "app_version";
ALTER TABLE "affiliate_visits" RENAME COLUMN "installReferrer" TO "install_referrer";
ALTER TABLE "affiliate_visits" RENAME COLUMN "rawQueryString" TO "raw_query_string";
ALTER TABLE "affiliate_visits" RENAME COLUMN "rawHeaders" TO "raw_headers";
ALTER TABLE "affiliate_visits" RENAME COLUMN "clientEventId" TO "client_event_id";
ALTER TABLE "affiliate_visits" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "affiliate_disbursements" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "affiliate_disbursements" RENAME COLUMN "grossAmount" TO "gross_amount";
ALTER TABLE "affiliate_disbursements" RENAME COLUMN "netAmount" TO "net_amount";
ALTER TABLE "affiliate_disbursements" RENAME COLUMN "providerRef" TO "provider_ref";
ALTER TABLE "affiliate_disbursements" RENAME COLUMN "failureReason" TO "failure_reason";
ALTER TABLE "affiliate_disbursements" RENAME COLUMN "requestedAt" TO "requested_at";
ALTER TABLE "affiliate_disbursements" RENAME COLUMN "paidAt" TO "paid_at";
ALTER TABLE "affiliate_disbursements" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "affiliate_disbursements" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "commerce_transactions" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "commerce_transactions" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "commerce_transactions" RENAME COLUMN "productId" TO "product_id";
ALTER TABLE "commerce_transactions" RENAME COLUMN "itemTotal" TO "item_total";
ALTER TABLE "commerce_transactions" RENAME COLUMN "shippingTotal" TO "shipping_total";
ALTER TABLE "commerce_transactions" RENAME COLUMN "feeTotal" TO "fee_total";
ALTER TABLE "commerce_transactions" RENAME COLUMN "voucherAmount" TO "voucher_amount";
ALTER TABLE "commerce_transactions" RENAME COLUMN "voucherCode" TO "voucher_code";
ALTER TABLE "commerce_transactions" RENAME COLUMN "voucherId" TO "voucher_id";
ALTER TABLE "commerce_transactions" RENAME COLUMN "affiliatorId" TO "affiliator_id";
ALTER TABLE "commerce_transactions" RENAME COLUMN "programId" TO "program_id";
ALTER TABLE "commerce_transactions" RENAME COLUMN "attributedAffiliatorMemberId" TO "attributed_affiliator_member_id";
ALTER TABLE "commerce_transactions" RENAME COLUMN "providerEventId" TO "provider_event_id";
ALTER TABLE "commerce_transactions" RENAME COLUMN "paidAt" TO "paid_at";
ALTER TABLE "commerce_transactions" RENAME COLUMN "canceledAt" TO "canceled_at";
ALTER TABLE "commerce_transactions" RENAME COLUMN "expiredAt" TO "expired_at";
ALTER TABLE "commerce_transactions" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "commerce_transactions" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "commerce_payments" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "commerce_payments" RENAME COLUMN "transactionId" TO "transaction_id";
ALTER TABLE "commerce_payments" RENAME COLUMN "memberId" TO "member_id";
ALTER TABLE "commerce_payments" RENAME COLUMN "paymentType" TO "payment_type";
ALTER TABLE "commerce_payments" RENAME COLUMN "ewalletType" TO "ewallet_type";
ALTER TABLE "commerce_payments" RENAME COLUMN "acceptedAmount" TO "accepted_amount";
ALTER TABLE "commerce_payments" RENAME COLUMN "vendorStatus" TO "vendor_status";
ALTER TABLE "commerce_payments" RENAME COLUMN "externalId" TO "external_id";
ALTER TABLE "commerce_payments" RENAME COLUMN "xenditId" TO "xendit_id";
ALTER TABLE "commerce_payments" RENAME COLUMN "xenditPaymentMethodId" TO "xendit_payment_method_id";
ALTER TABLE "commerce_payments" RENAME COLUMN "paymentMethodId" TO "payment_method_id";
ALTER TABLE "commerce_payments" RENAME COLUMN "vaNumber" TO "va_number";
ALTER TABLE "commerce_payments" RENAME COLUMN "checkoutUrl" TO "checkout_url";
ALTER TABLE "commerce_payments" RENAME COLUMN "deeplinkUrl" TO "deeplink_url";
ALTER TABLE "commerce_payments" RENAME COLUMN "cardMaskedNumber" TO "card_masked_number";
ALTER TABLE "commerce_payments" RENAME COLUMN "cardBrand" TO "card_brand";
ALTER TABLE "commerce_payments" RENAME COLUMN "expiredAt" TO "expired_at";
ALTER TABLE "commerce_payments" RENAME COLUMN "paidAt" TO "paid_at";
ALTER TABLE "commerce_payments" RENAME COLUMN "logRequest" TO "log_request";
ALTER TABLE "commerce_payments" RENAME COLUMN "logResponse" TO "log_response";
ALTER TABLE "commerce_payments" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "commerce_payments" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "commerce_payment_events" RENAME COLUMN "paymentId" TO "payment_id";
ALTER TABLE "commerce_payment_events" RENAME COLUMN "fromStatus" TO "from_status";
ALTER TABLE "commerce_payment_events" RENAME COLUMN "toStatus" TO "to_status";
ALTER TABLE "commerce_payment_events" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "vouchers" RENAME COLUMN "legacyId" TO "legacy_id";
ALTER TABLE "vouchers" RENAME COLUMN "productId" TO "product_id";
ALTER TABLE "vouchers" RENAME COLUMN "maxAmount" TO "max_amount";
ALTER TABLE "vouchers" RENAME COLUMN "startsAt" TO "starts_at";
ALTER TABLE "vouchers" RENAME COLUMN "endsAt" TO "ends_at";
ALTER TABLE "vouchers" RENAME COLUMN "isActive" TO "is_active";
ALTER TABLE "vouchers" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "vouchers" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "admins" RENAME COLUMN "fullName" TO "full_name";
ALTER TABLE "admins" RENAME COLUMN "passwordHash" TO "password_hash";
ALTER TABLE "admins" RENAME COLUMN "isActive" TO "is_active";
ALTER TABLE "admins" RENAME COLUMN "lastLoginAt" TO "last_login_at";
ALTER TABLE "admins" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "admins" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "app_settings" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "app_settings" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "third_party_credentials" RENAME COLUMN "keyHash" TO "key_hash";
ALTER TABLE "third_party_credentials" RENAME COLUMN "isActive" TO "is_active";
ALTER TABLE "third_party_credentials" RENAME COLUMN "triggersAffiliate" TO "triggers_affiliate";
ALTER TABLE "third_party_credentials" RENAME COLUMN "canIngestRefund" TO "can_ingest_refund";
ALTER TABLE "third_party_credentials" RENAME COLUMN "lastUsedAt" TO "last_used_at";
ALTER TABLE "third_party_credentials" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "third_party_credentials" RENAME COLUMN "updatedAt" TO "updated_at";

-- ============================================================
-- 86 indexes / unique constraints
-- ============================================================
ALTER INDEX "members_legacyId_key" RENAME TO "members_legacy_id_key";
ALTER INDEX "members_googleSub_key" RENAME TO "members_google_sub_key";
ALTER INDEX "members_affiliateCode_key" RENAME TO "members_affiliate_code_key";
ALTER INDEX "member_profiles_memberId_key" RENAME TO "member_profiles_member_id_key";
ALTER INDEX "devices_memberId_deviceId_key" RENAME TO "devices_member_id_device_id_key";
ALTER INDEX "refresh_tokens_memberId_idx" RENAME TO "refresh_tokens_member_id_idx";
ALTER INDEX "refresh_tokens_memberId_clientType_revokedAt_idx" RENAME TO "refresh_tokens_member_id_client_type_revoked_at_idx";
ALTER INDEX "countries_legacyId_key" RENAME TO "countries_legacy_id_key";
ALTER INDEX "provinces_legacyId_key" RENAME TO "provinces_legacy_id_key";
ALTER INDEX "provinces_countryId_idx" RENAME TO "provinces_country_id_idx";
ALTER INDEX "cities_legacyId_key" RENAME TO "cities_legacy_id_key";
ALTER INDEX "cities_provinceId_idx" RENAME TO "cities_province_id_idx";
ALTER INDEX "districts_legacyId_key" RENAME TO "districts_legacy_id_key";
ALTER INDEX "districts_cityId_idx" RENAME TO "districts_city_id_idx";
ALTER INDEX "banners_legacyId_key" RENAME TO "banners_legacy_id_key";
ALTER INDEX "products_legacyId_key" RENAME TO "products_legacy_id_key";
ALTER INDEX "products_iapProductId_key" RENAME TO "products_iap_product_id_key";
ALTER INDEX "courses_productId_key" RENAME TO "courses_product_id_key";
ALTER INDEX "courses_legacyCourseId_key" RENAME TO "courses_legacy_course_id_key";
ALTER INDEX "course_enrollment_legacyId_key" RENAME TO "course_enrollment_legacy_id_key";
ALTER INDEX "course_enrollment_memberId_courseId_key" RENAME TO "course_enrollment_member_id_course_id_key";
ALTER INDEX "course_enrollment_memberId_createdAt_idx" RENAME TO "course_enrollment_member_id_created_at_idx";
ALTER INDEX "course_sections_legacySectionId_key" RENAME TO "course_sections_legacy_section_id_key";
ALTER INDEX "course_sections_courseId_order_idx" RENAME TO "course_sections_course_id_order_idx";
ALTER INDEX "course_lessons_legacyLessonId_key" RENAME TO "course_lessons_legacy_lesson_id_key";
ALTER INDEX "course_lessons_sectionId_order_idx" RENAME TO "course_lessons_section_id_order_idx";
ALTER INDEX "reviews_productId_memberId_key" RENAME TO "reviews_product_id_member_id_key";
ALTER INDEX "reviews_productId_stars_idx" RENAME TO "reviews_product_id_stars_idx";
ALTER INDEX "topics_legacyId_key" RENAME TO "topics_legacy_id_key";
ALTER INDEX "topics_networkId_idx" RENAME TO "topics_network_id_idx";
ALTER INDEX "topic_join_requests_topicId_memberId_key" RENAME TO "topic_join_requests_topic_id_member_id_key";
ALTER INDEX "topic_join_requests_memberId_idx" RENAME TO "topic_join_requests_member_id_idx";
ALTER INDEX "topic_subscriptions_memberId_topicId_key" RENAME TO "topic_subscriptions_member_id_topic_id_key";
ALTER INDEX "posts_legacyId_key" RENAME TO "posts_legacy_id_key";
ALTER INDEX "posts_authorId_idx" RENAME TO "posts_author_id_idx";
ALTER INDEX "posts_topicId_idx" RENAME TO "posts_topic_id_idx";
ALTER INDEX "post_likes_postId_memberId_key" RENAME TO "post_likes_post_id_member_id_key";
ALTER INDEX "post_reports_postId_idx" RENAME TO "post_reports_post_id_idx";
ALTER INDEX "comments_legacyId_key" RENAME TO "comments_legacy_id_key";
ALTER INDEX "comments_postId_idx" RENAME TO "comments_post_id_idx";
ALTER INDEX "comments_parentId_idx" RENAME TO "comments_parent_id_idx";
ALTER INDEX "comment_likes_commentId_memberId_key" RENAME TO "comment_likes_comment_id_member_id_key";
ALTER INDEX "networks_legacyId_key" RENAME TO "networks_legacy_id_key";
ALTER INDEX "network_member_requests_networkId_memberId_key" RENAME TO "network_member_requests_network_id_member_id_key";
ALTER INDEX "network_member_requests_memberId_idx" RENAME TO "network_member_requests_member_id_idx";
ALTER INDEX "network_banned_members_networkId_memberId_key" RENAME TO "network_banned_members_network_id_member_id_key";
ALTER INDEX "network_team_members_networkId_memberId_key" RENAME TO "network_team_members_network_id_member_id_key";
ALTER INDEX "network_team_members_memberId_idx" RENAME TO "network_team_members_member_id_idx";
ALTER INDEX "network_members_legacyId_key" RENAME TO "network_members_legacy_id_key";
ALTER INDEX "network_members_networkId_memberId_key" RENAME TO "network_members_network_id_member_id_key";
ALTER INDEX "network_tags_networkId_name_key" RENAME TO "network_tags_network_id_name_key";
ALTER INDEX "report_categories_legacyId_key" RENAME TO "report_categories_legacy_id_key";
ALTER INDEX "member_reports_targetId_idx" RENAME TO "member_reports_target_id_idx";
ALTER INDEX "member_reports_reporterId_idx" RENAME TO "member_reports_reporter_id_idx";
ALTER INDEX "notifications_dedupeKey_key" RENAME TO "notifications_dedupe_key_key";
ALTER INDEX "notifications_memberId_readAt_idx" RENAME TO "notifications_member_id_read_at_idx";
ALTER INDEX "notifications_memberId_networkId_idx" RENAME TO "notifications_member_id_network_id_idx";
ALTER INDEX "notifications_memberId_seenAt_idx" RENAME TO "notifications_member_id_seen_at_idx";
ALTER INDEX "notification_mutes_scope_refId_idx" RENAME TO "notification_mutes_scope_ref_id_idx";
ALTER INDEX "affiliate_programs_legacyId_key" RENAME TO "affiliate_programs_legacy_id_key";
ALTER INDEX "affiliate_programs_productId_idx" RENAME TO "affiliate_programs_product_id_idx";
ALTER INDEX "member_affiliators_legacyId_key" RENAME TO "member_affiliators_legacy_id_key";
ALTER INDEX "member_affiliators_memberId_programId_key" RENAME TO "member_affiliators_member_id_program_id_key";
ALTER INDEX "member_affiliators_programId_idx" RENAME TO "member_affiliators_program_id_idx";
ALTER INDEX "affiliate_commissions_legacyId_key" RENAME TO "affiliate_commissions_legacy_id_key";
ALTER INDEX "affiliate_commissions_recipientId_createdAt_idx" RENAME TO "affiliate_commissions_recipient_id_created_at_idx";
ALTER INDEX "affiliate_commissions_programId_idx" RENAME TO "affiliate_commissions_program_id_idx";
ALTER INDEX "affiliate_commissions_buyerMemberId_idx" RENAME TO "affiliate_commissions_buyer_member_id_idx";
ALTER INDEX "affiliate_visits_clientEventId_key" RENAME TO "affiliate_visits_client_event_id_key";
ALTER INDEX "affiliate_visits_programId_createdAt_idx" RENAME TO "affiliate_visits_program_id_created_at_idx";
ALTER INDEX "affiliate_visits_affiliatorMemberId_createdAt_idx" RENAME TO "affiliate_visits_affiliator_member_id_created_at_idx";
ALTER INDEX "affiliate_visits_memberId_idx" RENAME TO "affiliate_visits_member_id_idx";
ALTER INDEX "affiliate_visits_adId_idx" RENAME TO "affiliate_visits_ad_id_idx";
ALTER INDEX "affiliate_visits_utmCampaign_idx" RENAME TO "affiliate_visits_utm_campaign_idx";
ALTER INDEX "affiliate_disbursements_memberId_status_idx" RENAME TO "affiliate_disbursements_member_id_status_idx";
ALTER INDEX "commerce_transactions_legacyId_key" RENAME TO "commerce_transactions_legacy_id_key";
ALTER INDEX "commerce_transactions_provider_providerEventId_key" RENAME TO "commerce_transactions_provider_provider_event_id_key";
ALTER INDEX "commerce_transactions_memberId_createdAt_idx" RENAME TO "commerce_transactions_member_id_created_at_idx";
ALTER INDEX "commerce_transactions_expiredAt_idx" RENAME TO "commerce_transactions_expired_at_idx";
ALTER INDEX "commerce_payments_legacyId_key" RENAME TO "commerce_payments_legacy_id_key";
ALTER INDEX "commerce_payments_xenditId_key" RENAME TO "commerce_payments_xendit_id_key";
ALTER INDEX "commerce_payments_transactionId_idx" RENAME TO "commerce_payments_transaction_id_idx";
ALTER INDEX "commerce_payments_status_expiredAt_idx" RENAME TO "commerce_payments_status_expired_at_idx";
ALTER INDEX "commerce_payment_events_paymentId_createdAt_idx" RENAME TO "commerce_payment_events_payment_id_created_at_idx";
ALTER INDEX "vouchers_legacyId_key" RENAME TO "vouchers_legacy_id_key";
ALTER INDEX "third_party_credentials_keyHash_key" RENAME TO "third_party_credentials_key_hash_key";

-- ============================================================
-- 58 foreign key constraints
-- ============================================================
ALTER TABLE "members" RENAME CONSTRAINT "members_inviterId_fkey" TO "members_inviter_id_fkey";
ALTER TABLE "member_profiles" RENAME CONSTRAINT "member_profiles_memberId_fkey" TO "member_profiles_member_id_fkey";
ALTER TABLE "member_profiles" RENAME CONSTRAINT "member_profiles_countryId_fkey" TO "member_profiles_country_id_fkey";
ALTER TABLE "member_profiles" RENAME CONSTRAINT "member_profiles_provinceId_fkey" TO "member_profiles_province_id_fkey";
ALTER TABLE "member_profiles" RENAME CONSTRAINT "member_profiles_cityId_fkey" TO "member_profiles_city_id_fkey";
ALTER TABLE "member_profiles" RENAME CONSTRAINT "member_profiles_districtId_fkey" TO "member_profiles_district_id_fkey";
ALTER TABLE "devices" RENAME CONSTRAINT "devices_memberId_fkey" TO "devices_member_id_fkey";
ALTER TABLE "refresh_tokens" RENAME CONSTRAINT "refresh_tokens_memberId_fkey" TO "refresh_tokens_member_id_fkey";
ALTER TABLE "provinces" RENAME CONSTRAINT "provinces_countryId_fkey" TO "provinces_country_id_fkey";
ALTER TABLE "cities" RENAME CONSTRAINT "cities_provinceId_fkey" TO "cities_province_id_fkey";
ALTER TABLE "districts" RENAME CONSTRAINT "districts_cityId_fkey" TO "districts_city_id_fkey";
ALTER TABLE "courses" RENAME CONSTRAINT "courses_productId_fkey" TO "courses_product_id_fkey";
ALTER TABLE "course_enrollment" RENAME CONSTRAINT "course_enrollment_memberId_fkey" TO "course_enrollment_member_id_fkey";
ALTER TABLE "course_enrollment" RENAME CONSTRAINT "course_enrollment_courseId_fkey" TO "course_enrollment_course_id_fkey";
ALTER TABLE "course_sections" RENAME CONSTRAINT "course_sections_courseId_fkey" TO "course_sections_course_id_fkey";
ALTER TABLE "course_lessons" RENAME CONSTRAINT "course_lessons_sectionId_fkey" TO "course_lessons_section_id_fkey";
ALTER TABLE "reviews" RENAME CONSTRAINT "reviews_productId_fkey" TO "reviews_product_id_fkey";
ALTER TABLE "topics" RENAME CONSTRAINT "topics_networkId_fkey" TO "topics_network_id_fkey";
ALTER TABLE "topic_join_requests" RENAME CONSTRAINT "topic_join_requests_topicId_fkey" TO "topic_join_requests_topic_id_fkey";
ALTER TABLE "topic_subscriptions" RENAME CONSTRAINT "topic_subscriptions_memberId_fkey" TO "topic_subscriptions_member_id_fkey";
ALTER TABLE "topic_subscriptions" RENAME CONSTRAINT "topic_subscriptions_topicId_fkey" TO "topic_subscriptions_topic_id_fkey";
ALTER TABLE "posts" RENAME CONSTRAINT "posts_authorId_fkey" TO "posts_author_id_fkey";
ALTER TABLE "posts" RENAME CONSTRAINT "posts_topicId_fkey" TO "posts_topic_id_fkey";
ALTER TABLE "post_likes" RENAME CONSTRAINT "post_likes_postId_fkey" TO "post_likes_post_id_fkey";
ALTER TABLE "post_likes" RENAME CONSTRAINT "post_likes_memberId_fkey" TO "post_likes_member_id_fkey";
ALTER TABLE "post_reports" RENAME CONSTRAINT "post_reports_postId_fkey" TO "post_reports_post_id_fkey";
ALTER TABLE "post_reports" RENAME CONSTRAINT "post_reports_categoryId_fkey" TO "post_reports_category_id_fkey";
ALTER TABLE "comments" RENAME CONSTRAINT "comments_postId_fkey" TO "comments_post_id_fkey";
ALTER TABLE "comments" RENAME CONSTRAINT "comments_authorId_fkey" TO "comments_author_id_fkey";
ALTER TABLE "comments" RENAME CONSTRAINT "comments_parentId_fkey" TO "comments_parent_id_fkey";
ALTER TABLE "comment_likes" RENAME CONSTRAINT "comment_likes_commentId_fkey" TO "comment_likes_comment_id_fkey";
ALTER TABLE "comment_likes" RENAME CONSTRAINT "comment_likes_memberId_fkey" TO "comment_likes_member_id_fkey";
ALTER TABLE "network_member_requests" RENAME CONSTRAINT "network_member_requests_networkId_fkey" TO "network_member_requests_network_id_fkey";
ALTER TABLE "network_banned_members" RENAME CONSTRAINT "network_banned_members_networkId_fkey" TO "network_banned_members_network_id_fkey";
ALTER TABLE "network_members" RENAME CONSTRAINT "network_members_networkId_fkey" TO "network_members_network_id_fkey";
ALTER TABLE "network_tags" RENAME CONSTRAINT "network_tags_networkId_fkey" TO "network_tags_network_id_fkey";
ALTER TABLE "member_reports" RENAME CONSTRAINT "member_reports_categoryId_fkey" TO "member_reports_category_id_fkey";
ALTER TABLE "notifications" RENAME CONSTRAINT "notifications_memberId_fkey" TO "notifications_member_id_fkey";
ALTER TABLE "notification_mutes" RENAME CONSTRAINT "notification_mutes_memberId_fkey" TO "notification_mutes_member_id_fkey";
ALTER TABLE "affiliate_programs" RENAME CONSTRAINT "affiliate_programs_productId_fkey" TO "affiliate_programs_product_id_fkey";
ALTER TABLE "member_affiliators" RENAME CONSTRAINT "member_affiliators_memberId_fkey" TO "member_affiliators_member_id_fkey";
ALTER TABLE "member_affiliators" RENAME CONSTRAINT "member_affiliators_programId_fkey" TO "member_affiliators_program_id_fkey";
ALTER TABLE "affiliate_commissions" RENAME CONSTRAINT "affiliate_commissions_recipientId_fkey" TO "affiliate_commissions_recipient_id_fkey";
ALTER TABLE "affiliate_commissions" RENAME CONSTRAINT "affiliate_commissions_affiliatorId_fkey" TO "affiliate_commissions_affiliator_id_fkey";
ALTER TABLE "affiliate_commissions" RENAME CONSTRAINT "affiliate_commissions_programId_fkey" TO "affiliate_commissions_program_id_fkey";
ALTER TABLE "affiliate_commissions" RENAME CONSTRAINT "affiliate_commissions_productId_fkey" TO "affiliate_commissions_product_id_fkey";
ALTER TABLE "affiliate_visits" RENAME CONSTRAINT "affiliate_visits_programId_fkey" TO "affiliate_visits_program_id_fkey";
ALTER TABLE "affiliate_visits" RENAME CONSTRAINT "affiliate_visits_affiliatorMemberId_fkey" TO "affiliate_visits_affiliator_member_id_fkey";
ALTER TABLE "affiliate_disbursements" RENAME CONSTRAINT "affiliate_disbursements_memberId_fkey" TO "affiliate_disbursements_member_id_fkey";
ALTER TABLE "commerce_transactions" RENAME CONSTRAINT "commerce_transactions_memberId_fkey" TO "commerce_transactions_member_id_fkey";
ALTER TABLE "commerce_transactions" RENAME CONSTRAINT "commerce_transactions_productId_fkey" TO "commerce_transactions_product_id_fkey";
ALTER TABLE "commerce_transactions" RENAME CONSTRAINT "commerce_transactions_affiliatorId_fkey" TO "commerce_transactions_affiliator_id_fkey";
ALTER TABLE "commerce_transactions" RENAME CONSTRAINT "commerce_transactions_programId_fkey" TO "commerce_transactions_program_id_fkey";
ALTER TABLE "commerce_transactions" RENAME CONSTRAINT "commerce_transactions_voucherId_fkey" TO "commerce_transactions_voucher_id_fkey";
ALTER TABLE "commerce_payments" RENAME CONSTRAINT "commerce_payments_transactionId_fkey" TO "commerce_payments_transaction_id_fkey";
ALTER TABLE "commerce_payments" RENAME CONSTRAINT "commerce_payments_memberId_fkey" TO "commerce_payments_member_id_fkey";
ALTER TABLE "commerce_payment_events" RENAME CONSTRAINT "commerce_payment_events_paymentId_fkey" TO "commerce_payment_events_payment_id_fkey";
ALTER TABLE "vouchers" RENAME CONSTRAINT "vouchers_productId_fkey" TO "vouchers_product_id_fkey";
