/**
 * Stable machine-readable error codes.
 *
 * WHY THIS EXISTS
 * ---------------
 * `docs/api-envelope.md` promises the client: "`error.code` for branching,
 * `error.message` for display". Before this catalog that contract was inverted:
 * every exception class hardcodes one code per HTTP status (400 -> BAD_REQUEST,
 * 401 -> UNAUTHORIZED, ...), and `statusToCode()` in error.middleware.ts maps
 * the same way, so `error.code` was a pure function of the status line and
 * carried zero information the client didn't already have. 93 distinct messages
 * collapsed into BAD_REQUEST alone. The only way for a client to tell "OTP
 * expired" from "OTP locked" was to string-match `error.message` — the field
 * documented as display-only. That made `message` the de-facto API key, so
 * rewording it was a silent breaking change invisible to the type checker.
 *
 * HOW TO USE
 * ----------
 * Never construct an exception with a literal message. Use the factories in
 * `./factory`, which pull the Indonesian copy from `./error-messages`:
 *
 *     throw badRequest(ERROR_CODES.OTP_EXPIRED);
 *     throw notFound(ERROR_CODES.POST_NOT_FOUND);
 *     throw badRequest(ERROR_CODES.POST_CONTENT_TOO_LONG, { max: MAX_CONTENT_CHARS });
 *
 * The factory you pick decides the HTTP status; the code decides the wording.
 * One code therefore always renders one sentence, which is what lets the mobile
 * client display `error.message` verbatim.
 *
 * RULES
 * -----
 * - A code is a permanent part of the public API. Never rename or reuse one;
 *   add a new code and leave the old one in place until old app builds are gone.
 * - Codes describe the CONDITION, not the endpoint, so the same condition
 *   reached from two routes reports the same code (and the same sentence).
 * - Do NOT encode the HTTP status in the code — that is what the status is for.
 * - Dynamic values (limits, offending input, current state) belong in `details`,
 *   never interpolated into the message: the message is user-facing copy and
 *   must not leak internal enums, field names, or raw client input.
 * - Every code needs an entry in ERROR_MESSAGES — the Record type enforces it.
 */
export const ERROR_CODES = {
  // --- generic fallbacks (defaults of the exception classes) ------------------
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ID_FORMAT_INVALID: 'ID_FORMAT_INVALID',
  RELATED_RESOURCE_INVALID: 'RELATED_RESOURCE_INVALID',

  // --- session / token -------------------------------------------------------
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  BEARER_TOKEN_MISSING: 'BEARER_TOKEN_MISSING',
  MEMBER_TOKEN_REQUIRED: 'MEMBER_TOKEN_REQUIRED',
  ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REQUIRED: 'REFRESH_TOKEN_REQUIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',

  // --- credentials / grants --------------------------------------------------
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  CREDENTIALS_REQUIRED: 'CREDENTIALS_REQUIRED',
  INVALID_CLIENT_CREDENTIALS: 'INVALID_CLIENT_CREDENTIALS',
  CLIENT_CREDENTIALS_REQUIRED: 'CLIENT_CREDENTIALS_REQUIRED',
  UNSUPPORTED_GRANT_TYPE: 'UNSUPPORTED_GRANT_TYPE',
  CLIENT_CREDENTIALS_DISABLED: 'CLIENT_CREDENTIALS_DISABLED',
  MEMBER_INACTIVE: 'MEMBER_INACTIVE',
  PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
  PASSWORD_CONFIRMATION_MISMATCH: 'PASSWORD_CONFIRMATION_MISMATCH',
  PASSWORD_MUST_DIFFER: 'PASSWORD_MUST_DIFFER',

  // --- social sign-in --------------------------------------------------------
  SOCIAL_SIGNIN_NOT_CONFIGURED: 'SOCIAL_SIGNIN_NOT_CONFIGURED',
  SOCIAL_PROVIDER_UNSUPPORTED: 'SOCIAL_PROVIDER_UNSUPPORTED',
  SOCIAL_TOKEN_REQUIRED: 'SOCIAL_TOKEN_REQUIRED',
  GOOGLE_ID_TOKEN_INVALID: 'GOOGLE_ID_TOKEN_INVALID',
  GOOGLE_EMAIL_NOT_VERIFIED: 'GOOGLE_EMAIL_NOT_VERIFIED',
  APPLE_ID_TOKEN_INVALID: 'APPLE_ID_TOKEN_INVALID',
  EMAIL_IN_USE_UNVERIFIED: 'EMAIL_IN_USE_UNVERIFIED',

  // --- registration / account identity ---------------------------------------
  ACCOUNT_NOT_REGISTERED: 'ACCOUNT_NOT_REGISTERED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  PHONE_ALREADY_REGISTERED: 'PHONE_ALREADY_REGISTERED',
  USERNAME_ALREADY_REGISTERED: 'USERNAME_ALREADY_REGISTERED',
  EMAIL_OR_PHONE_ALREADY_REGISTERED: 'EMAIL_OR_PHONE_ALREADY_REGISTERED',
  EMAIL_OR_PHONE_REQUIRED: 'EMAIL_OR_PHONE_REQUIRED',

  // --- contact verification --------------------------------------------------
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  PHONE_ALREADY_VERIFIED: 'PHONE_ALREADY_VERIFIED',
  EMAIL_NOT_ON_FILE: 'EMAIL_NOT_ON_FILE',
  PHONE_NOT_ON_FILE: 'PHONE_NOT_ON_FILE',
  CONTACT_NOT_ON_FILE: 'CONTACT_NOT_ON_FILE',
  EMAIL_LOCKED_AFTER_VERIFICATION: 'EMAIL_LOCKED_AFTER_VERIFICATION',
  EMAIL_TAKEN_BY_OTHER_MEMBER: 'EMAIL_TAKEN_BY_OTHER_MEMBER',
  PHONE_TAKEN_BY_OTHER_MEMBER: 'PHONE_TAKEN_BY_OTHER_MEMBER',
  EMAIL_INVALID: 'EMAIL_INVALID',
  PHONE_INVALID: 'PHONE_INVALID',

  // --- OTP -------------------------------------------------------------------
  OTP_NOT_FOUND: 'OTP_NOT_FOUND',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_LOCKED: 'OTP_LOCKED',
  OTP_RESEND_TOO_SOON: 'OTP_RESEND_TOO_SOON',
  OTP_DAILY_LIMIT_REACHED: 'OTP_DAILY_LIMIT_REACHED',
  OTP_PURPOSE_UNKNOWN: 'OTP_PURPOSE_UNKNOWN',

  // --- profile ---------------------------------------------------------------
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  TARGET_MEMBER_NOT_FOUND: 'TARGET_MEMBER_NOT_FOUND',
  MEMBER_MUTED: 'MEMBER_MUTED',
  FULL_NAME_INVALID: 'FULL_NAME_INVALID',
  GENDER_INVALID: 'GENDER_INVALID',
  BIRTHDATE_INVALID: 'BIRTHDATE_INVALID',
  AGE_BELOW_MINIMUM: 'AGE_BELOW_MINIMUM',

  // --- account lifecycle -----------------------------------------------------
  CONFIRMATION_REQUIRED: 'CONFIRMATION_REQUIRED',
  DELETION_NOT_SCHEDULED: 'DELETION_NOT_SCHEDULED',
  DEVICE_NOT_REGISTERED: 'DEVICE_NOT_REGISTERED',

  // --- affiliate -------------------------------------------------------------
  AFFILIATOR_CODE_REQUIRED: 'AFFILIATOR_CODE_REQUIRED',
  AFFILIATOR_CODE_NOT_FOUND: 'AFFILIATOR_CODE_NOT_FOUND',
  AFFILIATE_SELF_CONNECT: 'AFFILIATE_SELF_CONNECT',
  AFFILIATE_MODE_REQUIRED: 'AFFILIATE_MODE_REQUIRED',
  AFFILIATE_MODE_INVALID: 'AFFILIATE_MODE_INVALID',
  AFFILIATE_PROGRAM_CODE_REQUIRED: 'AFFILIATE_PROGRAM_CODE_REQUIRED',
  AFFILIATE_PROGRAM_NOT_FOUND: 'AFFILIATE_PROGRAM_NOT_FOUND',
  AFFILIATE_PROGRAM_INACTIVE: 'AFFILIATE_PROGRAM_INACTIVE',
  AFFILIATE_PROGRAM_NAME_REQUIRED: 'AFFILIATE_PROGRAM_NAME_REQUIRED',
  AFFILIATE_ENROLL_PARAMS_REQUIRED: 'AFFILIATE_ENROLL_PARAMS_REQUIRED',

  // --- KYC -------------------------------------------------------------------
  KYC_NOT_APPROVED: 'KYC_NOT_APPROVED',
  KYC_EXPIRED: 'KYC_EXPIRED',
  KYC_IN_REVIEW: 'KYC_IN_REVIEW',
  KYC_ALREADY_APPROVED: 'KYC_ALREADY_APPROVED',
  KYC_BALANCE_INSUFFICIENT: 'KYC_BALANCE_INSUFFICIENT',
  KYC_REVERIFY_REQUIRED: 'KYC_REVERIFY_REQUIRED',
  KYC_PROVIDER_NOT_CONFIGURED: 'KYC_PROVIDER_NOT_CONFIGURED',

  // --- disbursement ----------------------------------------------------------
  BANK_ACCOUNT_MISSING: 'BANK_ACCOUNT_MISSING',
  DISBURSEMENT_ALREADY_PENDING: 'DISBURSEMENT_ALREADY_PENDING',
  DISBURSEMENT_NOT_ELIGIBLE: 'DISBURSEMENT_NOT_ELIGIBLE',
  DISBURSEMENT_AMOUNT_EXCEEDS_BALANCE: 'DISBURSEMENT_AMOUNT_EXCEEDS_BALANCE',
  DISBURSEMENT_BELOW_MIN_BALANCE: 'DISBURSEMENT_BELOW_MIN_BALANCE',
  DISBURSEMENT_NET_TOO_SMALL: 'DISBURSEMENT_NET_TOO_SMALL',

  // --- commerce --------------------------------------------------------------
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSACTION_NOT_OWNED: 'TRANSACTION_NOT_OWNED',
  TRANSACTION_NOT_PENDING: 'TRANSACTION_NOT_PENDING',
  TRANSACTION_NOT_CANCELABLE: 'TRANSACTION_NOT_CANCELABLE',
  TRANSACTION_EXPIRED: 'TRANSACTION_EXPIRED',
  PAYMENT_IN_PROGRESS: 'PAYMENT_IN_PROGRESS',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_NOT_AVAILABLE: 'PRODUCT_NOT_AVAILABLE',
  PRODUCT_CODE_REQUIRED: 'PRODUCT_CODE_REQUIRED',
  PRODUCT_ALREADY_PURCHASED: 'PRODUCT_ALREADY_PURCHASED',
  VOUCHER_INVALID: 'VOUCHER_INVALID',
  VOUCHER_EXHAUSTED: 'VOUCHER_EXHAUSTED',

  // --- media -----------------------------------------------------------------
  MEDIA_TOKEN_MISSING: 'MEDIA_TOKEN_MISSING',
  MEDIA_TOKEN_INVALID: 'MEDIA_TOKEN_INVALID',
  MEDIA_TOKEN_EXPIRED: 'MEDIA_TOKEN_EXPIRED',
  MEDIA_AUTH_REQUIRED: 'MEDIA_AUTH_REQUIRED',
  MEDIA_RESOLUTION_INVALID: 'MEDIA_RESOLUTION_INVALID',
  MEDIA_HLS_UNAVAILABLE: 'MEDIA_HLS_UNAVAILABLE',
  COURSE_NOT_ENROLLED: 'COURSE_NOT_ENROLLED',

  // --- bonus -----------------------------------------------------------------
  BONUS_NOT_FOUND: 'BONUS_NOT_FOUND',
  BONUS_ID_INVALID: 'BONUS_ID_INVALID',

  // --- upload ----------------------------------------------------------------
  UPLOAD_FILE_MISSING: 'UPLOAD_FILE_MISSING',
  UPLOAD_EXTENSION_NOT_ALLOWED: 'UPLOAD_EXTENSION_NOT_ALLOWED',
  UPLOAD_NOT_IMAGE: 'UPLOAD_NOT_IMAGE',
  UPLOAD_IMAGE_INVALID: 'UPLOAD_IMAGE_INVALID',

  // --- post ------------------------------------------------------------------
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_ID_REQUIRED: 'POST_ID_REQUIRED',
  POST_EMPTY: 'POST_EMPTY',
  POST_CONTENT_TOO_LONG: 'POST_CONTENT_TOO_LONG',
  POST_TOO_MANY_IMAGES: 'POST_TOO_MANY_IMAGES',
  POST_DUPLICATE: 'POST_DUPLICATE',
  POST_NOT_PUBLISHED: 'POST_NOT_PUBLISHED',
  POST_DELETE_FORBIDDEN: 'POST_DELETE_FORBIDDEN',
  POST_CATEGORY_REQUIRED: 'POST_CATEGORY_REQUIRED',

  // --- comment ---------------------------------------------------------------
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  COMMENT_DELETED: 'COMMENT_DELETED',
  COMMENT_ID_REQUIRED: 'COMMENT_ID_REQUIRED',
  COMMENT_CONTENT_REQUIRED: 'COMMENT_CONTENT_REQUIRED',
  COMMENT_EMPTY: 'COMMENT_EMPTY',
  COMMENT_CONTENT_TOO_LONG: 'COMMENT_CONTENT_TOO_LONG',
  COMMENT_ON_UNPUBLISHED_POST: 'COMMENT_ON_UNPUBLISHED_POST',
  COMMENT_NOT_AUTHOR: 'COMMENT_NOT_AUTHOR',
  COMMENT_DELETE_FORBIDDEN: 'COMMENT_DELETE_FORBIDDEN',
  PARENT_COMMENT_NOT_FOUND: 'PARENT_COMMENT_NOT_FOUND',
  PARENT_COMMENT_POST_MISMATCH: 'PARENT_COMMENT_POST_MISMATCH',

  // --- network ---------------------------------------------------------------
  NETWORK_NOT_FOUND: 'NETWORK_NOT_FOUND',
  NETWORK_INACTIVE: 'NETWORK_INACTIVE',
  NETWORK_NOT_VISIBLE: 'NETWORK_NOT_VISIBLE',
  NETWORK_IDENTIFIER_REQUIRED: 'NETWORK_IDENTIFIER_REQUIRED',
  NETWORK_MEMBERSHIP_REQUIRED: 'NETWORK_MEMBERSHIP_REQUIRED',
  NETWORK_MEMBER_MUTED: 'NETWORK_MEMBER_MUTED',
  NETWORK_MEMBER_BANNED: 'NETWORK_MEMBER_BANNED',
  NETWORK_HELPDESK_JOIN_FORBIDDEN: 'NETWORK_HELPDESK_JOIN_FORBIDDEN',
  NETWORK_TEAM_ONLY: 'NETWORK_TEAM_ONLY',
  JOIN_REQUEST_NOT_FOUND: 'JOIN_REQUEST_NOT_FOUND',
  JOIN_REQUEST_ALREADY_RESOLVED: 'JOIN_REQUEST_ALREADY_RESOLVED',
  JOIN_REQUEST_PARAMS_REQUIRED: 'JOIN_REQUEST_PARAMS_REQUIRED',
  JOIN_REQUEST_MEMBER_BANNED: 'JOIN_REQUEST_MEMBER_BANNED',

  // --- topic -----------------------------------------------------------------
  TOPIC_NOT_FOUND: 'TOPIC_NOT_FOUND',
  TOPIC_INACTIVE: 'TOPIC_INACTIVE',
  TOPIC_ID_REQUIRED: 'TOPIC_ID_REQUIRED',
  TOPIC_NETWORK_MISMATCH: 'TOPIC_NETWORK_MISMATCH',
  TOPIC_PARENT_NETWORK_REQUIRED: 'TOPIC_PARENT_NETWORK_REQUIRED',
  TOPIC_SUBSCRIPTION_REQUIRED: 'TOPIC_SUBSCRIPTION_REQUIRED',

  // --- notification ----------------------------------------------------------
  NOTIFICATION_SCOPE_REQUIRED: 'NOTIFICATION_SCOPE_REQUIRED',
  NOTIFICATION_SCOPE_INVALID: 'NOTIFICATION_SCOPE_INVALID',

  // --- report ----------------------------------------------------------------
  REPORT_SELF_FORBIDDEN: 'REPORT_SELF_FORBIDDEN',
  REPORT_CATEGORY_INVALID: 'REPORT_CATEGORY_INVALID',
  REPORT_PARAMS_REQUIRED: 'REPORT_PARAMS_REQUIRED',

  // --- server-to-server (NOT shown to end users; see error-messages.ts) ------
  INGEST_CREDENTIAL_INVALID: 'INGEST_CREDENTIAL_INVALID',
  INGEST_EVENT_ID_REQUIRED: 'INGEST_EVENT_ID_REQUIRED',
  INGEST_TYPE_INVALID: 'INGEST_TYPE_INVALID',
  INGEST_REFUND_REFERENCE_REQUIRED: 'INGEST_REFUND_REFERENCE_REQUIRED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_TOKEN_INVALID: 'WEBHOOK_TOKEN_INVALID',
  WEBHOOK_AUTH_MISSING: 'WEBHOOK_AUTH_MISSING',
  WEBHOOK_AUTH_INVALID: 'WEBHOOK_AUTH_INVALID',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
